# Azure DevOps YAML pipeline for a Maven Java project
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Or windows-latest if you prefer Windows

steps:
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'https://github.com/MandlaRikhotso/Unit-test.git'
    testRunTitle: 'Maven Unit Tests'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-B'  # Batch mode
    goals: 'clean test'  # Run the clean and test phases
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    publishJUnitResults: true  # This ensures JUnit results are published in the build summary
    testResultsFiles: 'azure-pipelines.yaml'
